# provision.yml

- name: Provision machine
  hosts: "all"
  become: true
  
  tasks:
    - name: get hostname
      shell: hostname
      register: hostname

    - name: apt install basics
      apt: 
        pkg:
          - curl 
          - git 
          - zsh

    - name: Update all packages to the latest version
      apt:
        upgrade: dist

  roles:
    - role: "nickjj.docker"
      tags: ["docker"]
      vars:
        docker__edition: "ce"
        docker__channel: ["stable"]
        docker__version: "18.09.3"
        #docker__version: "18.06.1"

    - role: gantsign.oh-my-zsh
      users:
        - username: vagrant
          oh_my_zsh:
            theme: robbyrussell
            plugins:
              - git        